require("core.conf_plugins.lualine")
require("core.conf_plugins.colorscheme")
require("core.conf_plugins.nvim-tree")
require("core.conf_plugins.telescope")
require("core.conf_plugins.treesitter")
require("core.conf_plugins.lsp_config")
require("core.conf_plugins.completions")
