require("core.conf_plugins.lualine")
require("core.conf_plugins.colorscheme")
require("core.conf_plugins.nvim-tree")
require("core.conf_plugins.telescope")
require("core.conf_plugins.treesitter")
require("core.conf_plugins.coc")
require("core.conf_plugins.lspconfig")
